images:
  integrationOperator:
    repository: registry.gitlab.com/bitspur/internal/integration-operator
    tag: 0.2.0

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  debug: false
  replicas: 1
  maxConcurrentReconciles: 3
  integrationOperator:
    resources:
      enabled: defaults
      requests:
        cpu: 100m
        memory: 20Mi
      limits:
        cpu: 200m
        memory: 60Mi
