images:
  integrationOperator:
    repository: registry.gitlab.com/risserlabs/internal/integration-operator
    tag: 0.1.2

config:
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  debug: false
  maxConcurrentReconciles: 3
  integrationOperator:
    resources:
      enabled: defaults
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
