apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "integration-operator.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "integration-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "integration-operator.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "integration-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "integration-operator.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "integration-operator.name" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "integration-operator.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "integration-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - impersonate
  - apiGroups:
      - integration.rock8s.com
    resources:
      - plugs
      - sockets
    verbs:
      - "*"
  - apiGroups:
      - integration.rock8s.com
    resources:
      - plugs/status
      - sockets/status
    verbs:
      - get
      - update
      - patch
  - apiGroups:
      - integration.rock8s.com
    resources:
      - plugs/finalizers
      - sockets/finalizers
    verbs:
      - update
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
