# permissions for end users to edit deferredresources.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: deferredresource-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: integration-operator
    app.kubernetes.io/part-of: integration-operator
    app.kubernetes.io/managed-by: kustomize
  name: deferredresource-editor-role
rules:
- apiGroups:
  - integration.rock8s.com
  resources:
  - deferredresources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.rock8s.com
  resources:
  - deferredresources/status
  verbs:
  - get
