# permissions for end users to edit integrationplugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationplug-editor-role
rules:
  - apiGroups:
      - integration.siliconhills.dev
    resources:
      - integrationplugs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.siliconhills.dev
    resources:
      - integrationplugs/status
    verbs:
      - get
