# permissions for end users to view integrationsockets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: integrationsocket-viewer-role
rules:
  - apiGroups:
      - integration.siliconhills.dev
    resources:
      - integrationsockets
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - integration.siliconhills.dev
    resources:
      - integrationsockets/status
    verbs:
      - get
