# permissions for end users to view plugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plug-viewer-role
rules:
- apiGroups:
  - integration.siliconhills.dev
  resources:
  - plugs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integration.siliconhills.dev
  resources:
  - plugs/status
  verbs:
  - get
