# permissions for end users to edit plugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plug-editor-role
rules:
  - apiGroups:
      - integration.bitspur.com
    resources:
      - plugs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.bitspur.com
    resources:
      - plugs/status
    verbs:
      - get
