# permissions for end users to view plugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: plug-viewer-role
rules:
  - apiGroups:
      - integration.bitspur.com
    resources:
      - plugs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - integration.bitspur.com
    resources:
      - plugs/status
    verbs:
      - get
