# permissions for end users to edit plugs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: plug-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new
    app.kubernetes.io/part-of: new
    app.kubernetes.io/managed-by: kustomize
  name: plug-editor-role
rules:
- apiGroups:
  - integration.rock8s.com
  resources:
  - plugs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.rock8s.com
  resources:
  - plugs/status
  verbs:
  - get
