---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - interfaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - interfaces/finalizers
    verbs:
      - update
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - interfaces/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - plugs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - plugs/finalizers
    verbs:
      - update
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - plugs/status
    verbs:
      - get
      - patch
      - update
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - sockets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - sockets/finalizers
    verbs:
      - update
  - apiGroups:
      - integration.risserlabs.com
    resources:
      - sockets/status
    verbs:
      - get
      - patch
      - update
