
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - integration.bitspur.com
  resources:
  - interfaces
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.bitspur.com
  resources:
  - interfaces/finalizers
  verbs:
  - update
- apiGroups:
  - integration.bitspur.com
  resources:
  - interfaces/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integration.bitspur.com
  resources:
  - plugs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.bitspur.com
  resources:
  - plugs/finalizers
  verbs:
  - update
- apiGroups:
  - integration.bitspur.com
  resources:
  - plugs/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - integration.bitspur.com
  resources:
  - sockets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - integration.bitspur.com
  resources:
  - sockets/finalizers
  verbs:
  - update
- apiGroups:
  - integration.bitspur.com
  resources:
  - sockets/status
  verbs:
  - get
  - patch
  - update
