# permissions for end users to view sockets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: socket-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: new
    app.kubernetes.io/part-of: new
    app.kubernetes.io/managed-by: kustomize
  name: socket-viewer-role
rules:
- apiGroups:
  - integration.rock8s.com
  resources:
  - sockets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - integration.rock8s.com
  resources:
  - sockets/status
  verbs:
  - get
