# permissions for end users to edit sockets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: socket-editor-role
rules:
  - apiGroups:
      - integration.bitspur.com
    resources:
      - sockets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - integration.bitspur.com
    resources:
      - sockets/status
    verbs:
      - get
