apiVersion: integration.siliconhills.dev/v1alpha2
kind: Plug
metadata:
  name: plug-sample
spec: 
  interface:
    name: hello
  interfaceVersions: '*'
  meta: |
    hello: world
  configEndpoint: http://localhost:3000/config
  configMapper: |
    hello: resource.spec.meta.hello.world
    howdy: meta.hello.world
  namespaceScope: '*'
  socket:
    name: hello
    namespace: world
  vars: []
