apiVersion: integration.siliconhills.dev/v1alpha2
kind: Plug
metadata:
  name: plug-sample
  namespace: integration-test
spec: 
  interface:
    name: interface-sample
    namespace: integration-test
  interfaceVersions: '*'
  meta: |
    hello: world
  configEndpoint: http://localhost:3000/config
  configMapper: |
    hello: resource.spec.meta.hello.world
    howdy: meta.hello.world
  namespaceScope: '*'
  socket:
    name: socket-sample
    namespace: integration-test
  vars: []
