apiVersion: integration.siliconhills.dev/v1alpha2
kind: Plug
metadata:
  name: plug-sample
  namespace: integration-test
spec: 
  namespaceScope: '*'
  interfaceVersions: '*'
  interface:
    name: interface-sample
    namespace: integration-test
  apparatus:
    endpoint: /plug
    idleTimeout: 60
    containers:
      - image: siliconhills/example-apparatus:latest
        imagePullPolicy: Always
        name: apparatus
        ports:
          - containerPort: 3000
            name: container
            protocol: TCP
  socket:
    name: socket-sample
    namespace: integration-test
  data:
    database: hello
  configMapper:
    interfaceName: vars.INTERFACE_NAME
  resources:
    - when: updated
      do: apply
      resource: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: hello
        data:
          hello: world
          interfaceName: {{ .plugConfig.interfaceName }}
  vars:
    - name: INTERFACE_NAME
      objref:
        apiVersion: integration.siliconhills.dev/v1alpha2
        kind: Interface
        name: interface-sample
      fieldref:
        fieldPath: 'metadata.name'
