apiVersion: integration.bitspur.com/v1alpha2
kind: Plug
metadata:
  name: plug-sample
  namespace: integration-test1
spec:
  interfaceVersions: "*"
  interface:
    name: interface-sample
    namespace: integration-test1
  apparatus:
    endpoint: /plug
    idleTimeout: 60
    containers:
      - image: bitspur/example-apparatus:latest
        imagePullPolicy: Always
        name: apparatus
        ports:
          - containerPort: 3000
            name: container
            protocol: TCP
  socket:
    name: socket-sample
    namespace: integration-test1
  data:
    database: hello
  configMapper:
    interfaceName: vars.INTERFACE_NAME
  resources:
    - when: updated
      do: apply
      resource: |
        apiVersion: v1
        kind: ConfigMap
        metadata:
          name: hello
        data:
          hello: world
          interfaceName: {{ .plugConfig.interfaceName }}
  vars:
    - name: INTERFACE_NAME
      objref:
        apiVersion: integration.bitspur.com/v1alpha2
        kind: Interface
        name: interface-sample
      fieldref:
        fieldPath: "metadata.name"
