apiVersion: integration.rock8s.com/v1beta1
kind: Plug
metadata:
  labels:
    app.kubernetes.io/name: plug
    app.kubernetes.io/instance: plug-sample
    app.kubernetes.io/part-of: new
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: new
  name: plug-sample
spec:
  socket:
    name: socket-sample
  config:
    howdy: texas
  resources:
    - when: [coupled, updated]
      do: apply
      templates:
        - apiVersion: v1
          kind: ConfigMap
          metadata:
            name: hello
          data:
            hello: '{% .socketConfig.hello %}'
            howdy: '{% .plugConfig.howdy %}'
  # apparatus:
  #   endpoint: /plug
  #   idleTimeout: 60
  #   containers:
  #     - image: bitspur/example-apparatus:latest
  #       imagePullPolicy: Always
  #       name: apparatus
  #       ports:
  #         - containerPort: 3000
  #           name: container
  #           protocol: TCP
  # data:
  #   database: hello
  # configTemplate:
  #   interfaceName: vars.INTERFACE_NAME
  # vars:
  #   - name: INTERFACE_NAME
  #     objref:
  #       apiVersion: integration.rock8s.com/v1alpha2
  #       kind: Interface
  #       name: interface-sample
  #     fieldref:
  #       fieldPath: "metadata.name"
