apiVersion: integration.siliconhills.dev/v1alpha2
kind: Socket
metadata:
  name: socket-sample
  namespace: integration-test
spec: 
  interface:
    name: interface-sample
    namespace: integration-test
