apiVersion: integration.siliconhills.dev/v1alpha2
kind: Plug
metadata:
  name: plug-sample
  namespace: integration-test
spec: 
  namespaceScope: '*'
  interfaceVersions: '*'
  interface:
    name: interface-sample
    namespace: integration-test
  integrationEndpoint: localhost:3000/plug
  socket:
    name: socket-sample
    namespace: integration-test
  data:
    database: hello
