apiVersion: integration.rock8s.com/v1beta1
kind: Socket
metadata:
  name: postgres
  namespace: postgres-namespace
spec:
  interface:
    config:
      socket:
        protocol:
          required: true
        username:
          required: true
        password:
          required: true
        hostname:
          required: true
        port:
          required: true
      plug:
        database:
          required: true
  config:
    protocol: psql
    username: postgres
    hostname: postgres-service.postgres-namespace.svc.cluster.local
    port: "5432"
  configSecretName: postgres-secret
  resources:
    - when: [coupled, updated]
      do: recreate
      resource: |
        apiVersion: batch/v1
        kind: Job
        metadata:
          name: postgres-coupled-or-updated-{% .plug.metadata.namespace %}
        spec:
          template:
            spec:
              containers:
                - name: psql
                  image: registry.gitlab.com/bitspur/rock8s/images/kube-commands-psql:0.0.1
                  env:
                    - name: POSTGRES_PROTOCOL
                      value: '{% .socketConfig.protocol %}'
                    - name: POSTGRES_USERNAME
                      value: '{% .socketConfig.username %}'
                    - name: POSTGRES_HOSTNAME
                      value: '{% .socketConfig.hostname %}'
                    - name: POSTGRES_PORT
                      value: '{% .socketConfig.port %}'
                    - name: POSTGRES_DATABASE
                      value: '{% .plugConfig.database %}'
                    - name: POSTGRES_PASSWORD
                      value: '{% .socketConfig.password %}'
                  command:
                    - sh
                    - -c
                    - |
                        export PGPASSFILE="/tmp/.pgpass"
                        export STDOUT="/tmp/createdb.out"
                        echo "*:*:*:*:$POSTGRES_PASSWORD" > $PGPASSFILE
                        chmod 600 $PGPASSFILE
                        createdb -h $POSTGRES_HOSTNAME -U $POSTGRES_USERNAME -p $POSTGRES_PORT -w $POSTGRES_DATABASE || true
