apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: plug-role
  namespace: default
rules:
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: plug-rolebinding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: plug-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
