images:
  integrationOperator:
    repository: codejamninja/integration-operator
    tag: 0.0.6

config:
  clusterProvider: infrastructure
  imagePullPolicy: IfNotPresent
  updateStrategy: RollingUpdate
  integrationOperator:
    baseUrl: ''
    hostname: ''
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
