apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationPlug
metadata:
  name: some-plug
  namespace: tmp-plug
spec:
  socket:
    name: some-socket
    namespace: tmp-socket
  replications:
    - version: v1
      kind: Secret
      name: some-secret2
    - version: v1
      kind: ConfigMap
      name: some-configmap2
  # kustomization: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret2
  namespace: tmp-plug
type: Opaque
stringData:
  howdy: texas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap2
  namespace: tmp-plug
data:
  howdy: texas
