apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationPlug
metadata:
  name: some-plug
  namespace: tmp-plug
spec:
  socket:
    name: some-socket
    namespace: tmp-socket
  # mergeConfigmaps:
  #   - from: some-configmap2
  #     to: some-configmap
  mergeSecrets:
    - from: some-secret2
      to: some-secret
  #  kustomization: {}
  #  replications:
  #    - from:
  #        group: string
  #        kind: string
  #        name: string
  #        version: string
  #      to:
  #        name: string
  #        namespace: string
  secretPostfix: s
  configmapPostfix: s
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret2
  namespace: tmp-plug
type: Opaque
stringData:
  howdy: texas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap2
  namespace: tmp-plug
data:
  howdy: texas
