apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationPlug
metadata:
  name: some-plug
  namespace: tmp-plug
spec:
  socket:
    name: some-socket
    namespace: tmp-socket
  # replications:
  #   - group: string
  #     kind: string
  #     name: string
  #     version: string
  # kustomization: {}
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret2
  namespace: tmp-plug
type: Opaque
stringData:
  howdy: texas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap2
  namespace: tmp-plug
data:
  howdy: texas
