apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationPlug
metadata:
  name: some-plug
  namespace: tmp-plug
spec:
  socket:
    name: some-socket
    namespace: tmp-socket
  cleanup: false
  replications:
    - version: v1
      kind: Secret
      name: some-secret2
    - version: v1
      kind: ConfigMap
      name: some-configmap2
  kustomization:
    configuration:
      varReference:
        - version: v1
          kind: Secret
          path: stringData
    resources:
      - version: v1
        kind: Secret
        name: some-secret2
        namespace: tmp-plug
      - version: v1
        kind: ConfigMap
        name: some-configmap-socket
        namespace: tmp-plug
      - version: v1
        kind: ConfigMap
        name: some-configmap-k
        namespace: tmp-plug
    patches:
      - patch: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: some-secret2
            namespace: tmp-plug
          type: Opaque
          stringData:
            hello: $(HELLO)
            foo: $(FOO)
    vars:
      - name: HELLO
        fieldref:
          fieldPath: data.hello
        objref:
          apiVersion: v1
          kind: ConfigMap
          name: some-configmap-socket
          namespace: tmp-plug
      - name: FOO
        fieldref:
          fieldPath: data.foo
        objref:
          apiVersion: v1
          kind: ConfigMap
          name: some-configmap-k
          namespace: tmp-plug
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap2
  namespace: tmp-plug
data:
  howdy: texas
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-socket-socket
  namespace: tmp-plug
data:
  foo: bar
