apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationSocket
metadata:
  name: some-socket
  namespace: tmp-socket
spec:
  # configmaps:
  #   - some-configmap
  secrets:
    - some-secret
  wait:
    timeout: 60000
    resources:
      - name: some-secret2
        version: v1
        kind: Secret
#  hooks:
#    - job: {}
#      messageRegex: string
#      name: string
#      timeout: int
#  replications:
#    - from:
#        group: string
#        kind: string
#        name: string
#        version: string
#      to:
#        name: string
#        namespace: string
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: tmp-socket
type: Opaque
stringData:
  hello: world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap
  namespace: tmp-socket
data:
  hello: world
