apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationSocket
metadata:
  name: some-socket
  namespace: tmp-socket
spec:
  # wait:
  #   timeout: 60000
  #   resources:
  #     - version: v1
  #       kind: Secret
  #       name: some-secret2
  replications:
    - version: v1
      kind: Secret
      name: some-secret
    - version: v1
      kind: ConfigMap
      name: some-configmap
  # hooks:
  #   - job: {}
  #     messageRegex: string
  #     name: string
  #     timeout: int
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: tmp-socket
type: Opaque
stringData:
  hello: world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap
  namespace: tmp-socket
data:
  hello: world
