apiVersion: integration.siliconhills.dev/v1alpha1
kind: IntegrationSocket
metadata:
  name: some-socket
  namespace: tmp-socket
spec:
  wait:
    timeout: 60000
    resources:
      - version: v1
        kind: Secret
        name: some-secret2
  replications:
    - version: v1
      kind: Secret
      name: some-secret
    - version: v1
      kind: ConfigMap
      name: some-configmap
  hooks:
    - job:
        template:
          spec:
            restartPolicy: Never
            containers:
              - name: some-job
                image: busybox
                command: ['cat', '/tmp/config/foo']
                volumeMounts:
                  - name: config
                    mountPath: /tmp/config
            volumes:
              - name: config
                configMap:
                  name: some-socket-socket
        backoffLimit: 4
      messageRegex: '/3\.14/g'
      name: create-or-update
      timeout: 60000
---
apiVersion: v1
kind: Secret
metadata:
  name: some-secret
  namespace: tmp-socket
type: Opaque
stringData:
  hello: world
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-configmap
  namespace: tmp-socket
data:
  hello: world
