apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "integration-operator.name" . }}
  labels:
    app.kubernetes.io/name: {{ template "integration-operator.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  selector:
    matchLabels:
      app: {{ template "integration-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.config.replicas }}
  strategy:
    type: {{ .Values.config.updateStrategy }}
  template:
    metadata:
      labels:
        app: {{ template "integration-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ template "integration-operator.name" . }}
      imagePullSecrets:
        - name: registry
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 89
              preference:
                matchExpressions:
                  - key: application/state
                    operator: In
                    values:
                      - stateless
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 90
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ template "integration-operator.name" . }}
                    - key: release
                      operator: In
                      values:
                        - {{ .Release.Name }}
      containers:
        - name: {{ template "integration-operator.name" . }}
          image: {{ .Values.images.integrationOperator.repository }}:{{ .Values.images.integrationOperator.tag }}
          imagePullPolicy: {{ .Values.config.imagePullPolicy }}
          args:
            - '--leader-elect'
            - '--health-probe-bind-address=:8081'
          resources:
{{- if (and .Values.config.integrationOperator.resources.enabled (not (eq .Values.config.integrationOperator.resources.enabled "false"))) }}
            requests:
{{ toYaml .Values.config.integrationOperator.resources.requests | indent 14 }}
            limits:
{{ toYaml .Values.config.integrationOperator.resources.limits | indent 14 }}
{{- else }}
            requests: {}
            limits: {}
{{- end }}
          env:
            - name: DEBUG_OPERATOR
              value: {{ .Values.config.debug | ternary "1" "0" | quote }}
            - name: MAX_CONCURRENT_RECONCILES
              value: {{ .Values.config.maxConcurrentReconciles | quote }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 10
